### ISSUE TITLE
CSS Tips

### ISSUE THREAD

**Issue by imsobear** [imsobear/blog#23]
整理一些CSS的用法。
#### 1. 清理浮动，出自[Nicolas Gallagher](http://nicolasgallagher.com/micro-clearfix-hack/)：

``` css
.cf:before, .cf:after {
    content:"";
    display:table;
}
.cf:after {
    clear:both;
}
.cf {
    zoom:1;
}
```
#### 2. 有`float:left/position:absolute`撑腰的情况下，`display`属性就是多余的:

如果给元素设置了`float:left/right` 或者 `position: absolute/fixed`，元素自动变为块级元素，但这个时候元素默认情况下宽度是内容的宽度，而不会充满整个父容器，不过因为是块级元素，宽度和上下边距都可以设置。
#### 3. 重置chrome下输入框的默认样式

``` css
input, button, select, textarea{
    outline:none;
}
textarea{
    resize:none;
} 
```
#### 4. z-index属性只有在定位元素上才会生效。

所谓定位元素，在`position: absolute`的解释里：设置了absolute的元素会根据已定位的父元素布局，已定位的元素指的就是position属性非`static`，即`relative`, `absolute`, 或者`fixed的元素`。
#### 5. iframe在IE8-下出现滚动条：

解决方法：`<iframe src="" scrolling="no" frameBorder="0"></iframe>`.
#### 6. IE7 下 `overflow: hidden` 失效：

解决方法：给容器设置 `position: relative`.
#### 7. css隐藏文字：

通常大家都会用`text-indent: -9999px`隐藏问在，但是这个方案在IE7和移动端会影响布局，所以推荐的方法是先给元素设置`overflow-y: hidden`，然后再设置一个比较大的`line-height`值，这样做还有一个好处就是可以复制这些文字。
#### 8. 根据窗口宽度切换`class`：

``` javascript
function changeClass () {
    var width = document.documentElement.clientWidth;
    if (width >= 1190) {
        return;
    } else if (width >= 990 && width <= 1190) {
        document.body.className = 'screen-width-1190';
    } else if (width < 990) {
        document.body.className = 'screen-width-768';
    }
}
changeClass();
window.onresize = function () {
    setTimeout(function () {
        changeClass();
    }, 500);
};
```
#### 9. overflow失效:

在IE6、7中，给父元素设置了`overflow: hidden;`，这时候如果子元素设置了`position`属性，则隐藏滚动条会失效，解决方案就是给父元素设置`position: relative`:

``` css
body{
    overflow: hidden;
    *position: relative;  /* IE hack */
}
child{
    position: relative;
}
```
